package com.austinramsay.javajotter.gui;

import com.austinramsay.javajotter.JavaJotter;

public class LoginWindow extends javax.swing.JFrame {

	private JavaJotter controller;

    public LoginWindow(JavaJotter controller) {
		this.controller = controller;
        initComponents();
		setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        srvAddrLabel = new javax.swing.JLabel();
        srvAddrField = new javax.swing.JTextField();
        srvPortLabel = new javax.swing.JLabel();
        srvPortField = new javax.swing.JTextField();
        rUserLabel = new javax.swing.JLabel();
        rUserCheckbox = new javax.swing.JCheckBox();
        rSrvInfoLabel = new javax.swing.JLabel();
        rSrvInfoCheckbox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaJotter");

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));

        loginLabel.setFont(new java.awt.Font("Dialog", 1, 16));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("JavaJotter Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(loginButton);

        registerButton.setText("Register");
        jPanel2.add(registerButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jPanel3.setLayout(new java.awt.GridLayout(6, 2));

        usernameLabel.setText("Username:");
        jPanel3.add(usernameLabel);

        usernameField.setText("aramsay");
        jPanel3.add(usernameField);

        passwordLabel.setText("Password:");
        jPanel3.add(passwordLabel);

        passwordField.setText("password");
        jPanel3.add(passwordField);

        srvAddrLabel.setText("Server address:");
        jPanel3.add(srvAddrLabel);

        srvAddrField.setText("helios");
        jPanel3.add(srvAddrField);

        srvPortLabel.setText("Server port:");
        jPanel3.add(srvPortLabel);

        srvPortField.setText("7800");
        jPanel3.add(srvPortField);

        rUserLabel.setText("Remember username?");
        jPanel3.add(rUserLabel);
        jPanel3.add(rUserCheckbox);

        rSrvInfoLabel.setText("Remember server info?");
        jPanel3.add(rSrvInfoLabel);
        jPanel3.add(rSrvInfoCheckbox);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
		controller.login(
				usernameField.getText(), 
				passwordField.getPassword(),
				srvAddrField.getText(),
				srvPortField.getText());
	}//GEN-LAST:event_loginButtonActionPerformed

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		System.exit(0);
	}//GEN-LAST:event_cancelButtonActionPerformed

	public void loginButtonEnabled(boolean value) {
		loginButton.setEnabled(value);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JCheckBox rSrvInfoCheckbox;
    private javax.swing.JLabel rSrvInfoLabel;
    private javax.swing.JCheckBox rUserCheckbox;
    private javax.swing.JLabel rUserLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField srvAddrField;
    private javax.swing.JLabel srvAddrLabel;
    private javax.swing.JTextField srvPortField;
    private javax.swing.JLabel srvPortLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables

}
