/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewNoteWindow.java
 *
 * Created on Apr 7, 2025, 2:17:41 PM
 */

package com.austinramsay.javajotter.gui;

import com.austinramsay.javajotter.ContentManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.AbstractAction;
import javax.swing.Action;

/**
 *
 * @author aramsay
 */
public class NewNbWindow extends javax.swing.JFrame {

	private ContentManager cntMgr;
	private Integer parentId;
	private Action createNbAction;

    /** Creates new form NewNoteWindow */
    public NewNbWindow(ContentManager cntMgr, java.awt.Component c, Integer parentId, String assocNbTitle) {
		this.cntMgr = cntMgr;
		this.parentId = parentId;

		createNbAction = new CreateNotebookAction("Create");

        initComponents();

		parentNbLabel.setText(assocNbTitle);
		createButton.setEnabled(false);

		super.setLocationRelativeTo(c);
		setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        parentNbPrintedLabel = new javax.swing.JLabel();
        parentNbLabel = new javax.swing.JLabel();
        nbTitleLabel = new javax.swing.JLabel();
        nbTitleInput = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JavaJotter Note");
        setMinimumSize(new java.awt.Dimension(310, 140));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Create a New Notebook"));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        parentNbPrintedLabel.setText("Parent notebook:");
        jPanel1.add(parentNbPrintedLabel);

        parentNbLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        parentNbLabel.setText("(set notebook title here)");
        parentNbLabel.setMaximumSize(null);
        parentNbLabel.setMinimumSize(null);
        parentNbLabel.setPreferredSize(null);
        jPanel1.add(parentNbLabel);

        nbTitleLabel.setText("Notebook title:");
        jPanel1.add(nbTitleLabel);

        nbTitleInput.setAction(createNbAction);
        nbTitleInput.setMinimumSize(null);
        nbTitleInput.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                setCreateButtonState();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                setCreateButtonState();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                setCreateButtonState();
            }

            private void setCreateButtonState() {
                createButton.setEnabled(
                    !nbTitleInput.getText().trim().isEmpty());
            }
        });
        jPanel1.add(nbTitleInput);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        createButton.setAction(createNbAction);
        jPanel2.add(createButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		super.dispose();
	}//GEN-LAST:event_cancelButtonActionPerformed

	private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
		super.requestFocus();
		super.toFront();
		super.setAlwaysOnTop(true);
	}//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nbTitleInput;
    private javax.swing.JLabel nbTitleLabel;
    private javax.swing.JLabel parentNbLabel;
    private javax.swing.JLabel parentNbPrintedLabel;
    // End of variables declaration//GEN-END:variables

	class CreateNotebookAction extends AbstractAction {
		public CreateNotebookAction(String label) {
			super(label);
		}

		@Override
		public void actionPerformed(java.awt.event.ActionEvent e) {
			if (!nbTitleInput.getText().trim().isEmpty()) {
				cntMgr.newLocalNotebook(parentId, nbTitleInput.getText());
				dispose();
			}
		}
	}

}
