/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewNoteWindow.java
 *
 * Created on Apr 7, 2025, 2:17:41 PM
 */

package com.austinramsay.javajotter.gui;

import com.austinramsay.javajotter.ContentManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.Action;
import javax.swing.AbstractAction;

/**
 *
 * @author aramsay
 */
public class NewNoteWindow extends javax.swing.JFrame {

	private ContentManager cntMgr;
	private Integer nbId;
	private Action createNoteAction;

    /** Creates new form NewNoteWindow */
    public NewNoteWindow(ContentManager cntMgr, java.awt.Component c, Integer nbId, String assocNbTitle) {
		this.cntMgr = cntMgr;
		this.nbId = nbId;

		createNoteAction = new CreateNoteAction("Create");

        initComponents();

		assocNbLabel.setText(assocNbTitle);
		createButton.setEnabled(false);

		super.setLocationRelativeTo(c);
		setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        assocNbPrintedLabel = new javax.swing.JLabel();
        assocNbLabel = new javax.swing.JLabel();
        noteTitleLabel = new javax.swing.JLabel();
        noteTitleInput = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JavaJotter Note");
        setMinimumSize(new java.awt.Dimension(310, 140));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Create a New Note"));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        assocNbPrintedLabel.setText("Associated notebook:");
        assocNbPrintedLabel.setMaximumSize(null);
        assocNbPrintedLabel.setMinimumSize(null);
        assocNbPrintedLabel.setPreferredSize(null);
        jPanel1.add(assocNbPrintedLabel);

        assocNbLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        assocNbLabel.setText("(set notebook title here)");
        assocNbLabel.setMaximumSize(null);
        assocNbLabel.setMinimumSize(null);
        assocNbLabel.setPreferredSize(null);
        jPanel1.add(assocNbLabel);

        noteTitleLabel.setText("Note title:");
        noteTitleLabel.setMaximumSize(null);
        noteTitleLabel.setMinimumSize(null);
        noteTitleLabel.setPreferredSize(null);
        jPanel1.add(noteTitleLabel);

        noteTitleInput.setAction(createNoteAction);
        noteTitleInput.setMinimumSize(null);
        noteTitleInput.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                setCreateButtonState();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                setCreateButtonState();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                setCreateButtonState();
            }

            private void setCreateButtonState() {
                createButton.setEnabled(
                    !noteTitleInput.getText().trim().isEmpty()
                );
            }
        });
        jPanel1.add(noteTitleInput);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        createButton.setAction(createNoteAction);
        createButton.setText("Create");
        createButton.setEnabled(false);
        jPanel2.add(createButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		super.dispose();
	}//GEN-LAST:event_cancelButtonActionPerformed

	private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
		super.requestFocus();
		super.toFront();
		super.setAlwaysOnTop(true);
	}//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel assocNbLabel;
    private javax.swing.JLabel assocNbPrintedLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField noteTitleInput;
    private javax.swing.JLabel noteTitleLabel;
    // End of variables declaration//GEN-END:variables

	class CreateNoteAction extends AbstractAction {
		public CreateNoteAction(String label) {
			super(label);
		}

		@Override
		public void actionPerformed(java.awt.event.ActionEvent e) {
			if (!noteTitleInput.getText().trim().isEmpty()) {
				cntMgr.newLocalNote(nbId, noteTitleInput.getText());
				dispose();
			}
		}
	}
}
