/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RenameContentWindow.java
 *
 * Created on Apr 18, 2025, 11:05:48 AM
 */

package com.austinramsay.javajotter.gui;

import com.austinramsay.javajotter.ContentManager;
import com.austinramsay.javajotterlibrary.Entity;
import javax.swing.border.TitledBorder;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;

/**
 *
 * @author aramsay
 */
public class RenameEntityWindow extends javax.swing.JFrame {

	private ContentManager cntMgr;
	private Entity entityType;
	private Integer entityId;
	private Action renameAction;

    /** Creates new form RenameContentWindow */
    public RenameEntityWindow(
			ContentManager cntMgr,
			java.awt.Component c,
			Entity entityType,
			Integer entityId,
			String currentEntityName) {
		this.cntMgr = cntMgr;
		this.entityType = entityType;
		this.entityId = entityId;

		renameAction = new RenameAction("Rename");

        initComponents();

		String borderTitle = "";
		if (entityType == Entity.NOTEBOOK) {
			borderTitle = "Rename Notebook";
		} else if (entityType == Entity.NOTE) {
			borderTitle="Rename Note";
		}
		TitledBorder border = (TitledBorder)jPanel1.getBorder();
		border.setTitle(borderTitle);

		currentNameLabel.setText(currentEntityName);

		renameButton.setEnabled(false);

		super.setLocationRelativeTo(c);
		setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        staticCurrentNameLabel = new javax.swing.JLabel();
        currentNameLabel = new javax.swing.JLabel();
        newNameLabel = new javax.swing.JLabel();
        newNameInput = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        renameButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JavaJotter Rename");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(310, 140));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("EntityType"));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        staticCurrentNameLabel.setText("Current name:");
        jPanel1.add(staticCurrentNameLabel);

        currentNameLabel.setText("SetCurrentName");
        jPanel1.add(currentNameLabel);

        newNameLabel.setText("New name:");
        jPanel1.add(newNameLabel);

        newNameInput.setAction(renameAction);
        newNameInput.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                setCreateButtonState();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                setCreateButtonState();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                setCreateButtonState();
            }

            private void setCreateButtonState() {
                renameButton.setEnabled(
                    !newNameInput.getText().trim().isEmpty());
            }
        });
        jPanel1.add(newNameInput);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        renameButton.setAction(renameAction);
        renameButton.setText("Rename");
        jPanel2.add(renameButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		super.dispose();
	}//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel currentNameLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField newNameInput;
    private javax.swing.JLabel newNameLabel;
    private javax.swing.JButton renameButton;
    private javax.swing.JLabel staticCurrentNameLabel;
    // End of variables declaration//GEN-END:variables

	class RenameAction extends AbstractAction {
		public RenameAction(String label) {
			super(label);
		}

		@Override
		public void actionPerformed(java.awt.event.ActionEvent e) {
			if (!newNameInput.getText().trim().isEmpty()) {
				if (entityType == Entity.NOTEBOOK) {
					cntMgr.renameLocalNotebook(entityId, newNameInput.getText());
				} else if (entityType == Entity.NOTE) {
					cntMgr.renameLocalNote(entityId, newNameInput.getText());
				}
				dispose();
			}
		}
	}
}
